// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
)

type Project struct {
	ID        int64
	Name      string
	Desc      sql.NullString
	CreatedTs int64
	UpdatedTs int64
}

type Unit struct {
	ID        int64
	ProjectID int64
	CreatedTs int64
	UpdatedTs int64
}
